# Generated by Django 3.1.4 on 2021-01-07 01:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210106_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-criado'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='conteúdo'),
        ),
    ]
